name: Deploy to our server on Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github source code
        uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependancy
        run: npm install
      
      - name: Build react
        run : npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Clear all files to s3 with AWS CLI
        run: |
          aws s3 rm \
            s3://pace-maker \
            --recursive
      
      - name: Copy build files to s3 with AWS CLI
        run: |
          aws s3 cp \
          build \
          s3://pace-maker \
          --recursive
            
        
